const Actions = {
        INITIALSTATE:'INITIALSTATE',


SIGNUP_REQUEST:'SIGNUP_REQUEST',
SIGNUP_REQUEST_SUCCESS:'SIGNUP_REQUEST_SUCCESS',
SIGNUP_REQUEST_FAILED:'SIGNUP_REQUEST_FAILED',




}

export default Actions;