const Actions = {
        INITIALSTATE:'INITIALSTATE',


SIGNUPREQUEST:'SIGNUPREQUEST',
SIGNUPREQUESTSUCCESS:'SIGNUPREQUESTSUCCESS',
SIGNUPREQUESTFAILED:'SIGNUPREQUESTFAILED',

SIGNUPPREQUEST:'SIGNUPPREQUEST',
SIGNUPPREQUESTSUCCESS:'SIGNUPPREQUESTSUCCESS',
SIGNUPPREQUESTFAILED:'SIGNUPPREQUESTFAILED',


LOGINREQUEST:'SIGNUPREQUEST',
LOGINREQUESTSUCCESS:'SIGNUPREQUESTSUCCESS',
LOGINREQUESTFAILED:'SIGNUPREQUESTFAILED',
 

 BLOODREQUEST:'BLOODREQUEST',
BLOODREQUESTSUCCESS:'BLOODREQUESTSUCCESS',
 BLOODREQUESTFAILED:'BLOODREQUESTFAILED',

 USERDATA:'USERDATA',
 USERDATASUCCESS:'USERDATASUCCESS',
 USERDATAFAILED:'USERDATAFAILED',




}

export default Actions;