const Actions = {
        INITIALSTATE:'INITIALSTATE',


SIGNUPREQUEST:'SIGNUPREQUEST',
SIGNUPREQUESTSUCCESS:'SIGNUPREQUESTSUCCESS',
SIGNUPREQUESTFAILED:'SIGNUPREQUESTFAILED',




}

export default Actions;